package com.northmark.vibescan.util

import com.northmark.vibescan.data.AssetRepository
import com.northmark.vibescan.engine.Diagnosis
import com.northmark.vibescan.service.BatteryGuardian
import com.northmark.vibescan.service.KioskModeManager
import java.text.SimpleDateFormat
import java.util.*

/**
 * ReportGenerator — Generates structured Markdown reports for site audits and maintenance.
 */
object ReportGenerator {

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())

    fun generateSiteAuditReport(
        repo: AssetRepository,
        kioskManager: KioskModeManager,
        batteryGuardian: BatteryGuardian,
        latestDiagnosis: Diagnosis?
    ): String {
        return buildString {
            appendLine("# VibeScan Site Audit Report")
            appendLine("Generated: ${dateFormat.format(Date())}")
            appendLine()

            // 1. Node Health Section
            appendLine("## 1. Node Health Summary")
            appendLine("| Metric | Status |")
            appendLine("| :--- | :--- |")
            appendLine("| **Kiosk Mode** | ${kioskManager.getStatus().name} |")
            
            val battery = batteryGuardian.state.value
            appendLine("| **Battery Level** | ${battery.level}% (${if (battery.isCharging) "Charging" else "Discharging"}) |")
            appendLine("| **Battery Temp** | ${"%.1f".format(battery.tempCelsius)}°C |")
            appendLine("| **Node ID** | ${repo.readableDatabase.path.hashCode().toUInt().toString(16).uppercase()} |")
            appendLine()

            // 2. Sensor Stability Section
            appendLine("## 2. Sensor Performance (JNI Bridge)")
            if (latestDiagnosis != null) {
                appendLine("| Metric | Value | Status |")
                appendLine("| :--- | :--- | :--- |")
                appendLine("| **Sample Rate** | ${"%.1f".format(latestDiagnosis.actualSampleRate)} Hz | ${if (latestDiagnosis.actualSampleRate > 95) "Stable" else "Drift Detected"} |")
                appendLine("| **Signal Confidence** | ${"%.1f".format(latestDiagnosis.signalConfidence)}% | ${if (latestDiagnosis.signalConfidence > 80) "High" else "Low"} |")
                appendLine("| **Mount Quality** | ${latestDiagnosis.mountingStatusLevel} | ${latestDiagnosis.mountingMessage} |")
            } else {
                appendLine("_No live engine data available for stability audit._")
            }
            appendLine()

            // 3. Asset Risks Section
            appendLine("## 3. Asset Risk Assessment")
            val assets = repo.getAllAssets()
            val alerts = repo.getUnresolvedAlerts()

            if (assets.isEmpty()) {
                appendLine("_No assets configured on this node._")
            } else {
                appendLine("| Asset Name | Last Health | ISO Zone | Risk Level |")
                appendLine("| :--- | :--- | :--- | :--- |")
                assets.forEach { asset ->
                    val lastReading = repo.getRecentReadings(asset.id, 1).firstOrNull()
                    val risk = when {
                        lastReading == null -> "UNKNOWN"
                        lastReading.health < 40 -> "CRITICAL"
                        lastReading.health < 70 -> "WARNING"
                        else -> "NORMAL"
                    }
                    appendLine("| ${asset.name} | ${lastReading?.health ?: "N/A"} | ${lastReading?.isoZone ?: "N/A"} | $risk |")
                }
            }
            appendLine()

            // 4. Critical Alerts Section
            if (alerts.isNotEmpty()) {
                appendLine("### Active Maintenance Alerts")
                alerts.forEach { alert ->
                    appendLine("- **${alert.assetName}**: ${alert.faultLabel} (${alert.severity}) — _Action: ${alert.action}_")
                }
            } else {
                appendLine("### Active Maintenance Alerts")
                appendLine("_No unresolved alerts detected._")
            }
            appendLine()

            appendLine("---")
            appendLine("Report generated by VibeScan V4 Engine.")
        }
    }
}
